# Generated by Django 5.2.14 on 2026-06-03 12:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Класс/Тип объекта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Класс строительства',
                'verbose_name_plural': 'Классы строительства',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назначение')),
                ('apartments_area_ratio', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='0.000–1.000. Например, 0.750 = 75% от общей площади.', max_digits=4, verbose_name='Доля площади квартир')),
            ],
            options={
                'verbose_name': 'Функциональное назначение',
                'verbose_name_plural': 'Функциональные назначения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Например, 0.0732', max_digits=6, verbose_name='Ставка инфляции')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Инфляция',
                'verbose_name_plural': 'Инфляция',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation_clean_coef', models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=4, verbose_name='Коэф. очистки от инфляции')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройка расчёта',
                'verbose_name_plural': 'Настройки расчёта',
            },
        ),
        migrations.CreateModel(
            name='SocialNorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqm_per_doo_seat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='м² на место ДОО')),
                ('cost_per_doo_seat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость места ДОО, ₽')),
                ('sqm_per_school_seat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='м² на место СОШ')),
                ('cost_per_school_seat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость места СОШ, ₽')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Норматив социалки',
                'verbose_name_plural': 'Нормативы социалки',
            },
        ),
        migrations.CreateModel(
            name='ConstructionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors_min', models.PositiveIntegerField(verbose_name='Этажей от')),
                ('floors_max', models.PositiveIntegerField(verbose_name='Этажей до')),
                ('months', models.PositiveIntegerField(verbose_name='Срок, мес.')),
                ('building_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.buildingclass', verbose_name='Класс')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.buildingpurpose', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Срок строительства',
                'verbose_name_plural': 'Сроки строительства',
                'ordering': ['purpose__name', 'building_class__order', 'floors_min'],
            },
        ),
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_space', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость машиноместа, ₽')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.city', unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Тариф наземного паркинга',
                'verbose_name_plural': 'Наземный паркинг (тарифы)',
            },
        ),
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за м², ₽')),
                ('building_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.buildingclass', verbose_name='Класс')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Себестоимость',
                'verbose_name_plural': 'Себестоимость (таблица)',
                'ordering': ['city__name', 'building_class__order'],
                'unique_together': {('city', 'building_class')},
            },
        ),
    ]
